export interface Question {
  author: string;
  profileImage: string;
  question: string;
  date: string;
  replies?: Question[];
  isAdmin?: boolean;
  likes?: number;
  dislikes?: number;
}

const exampleQuestions: Question[] = [
  {
    author: "Alice",
    profileImage: "https://i.pravatar.cc/150?img=1",
    question: "Is this product durable?",
    date: "2025-07-06",
    likes: 12,
    dislikes: 1,
    replies: [
      {
        author: "Admin Support",
        profileImage: "https://i.pravatar.cc/150?img=50",
        question: "Yes, this product is tested for long-term durability.",
        date: "2025-07-07",
        isAdmin: true,
        likes: 6,
        dislikes: 0,
      },
      {
        author: "Carol",
        profileImage: "https://i.pravatar.cc/150?img=3",
        question: "Mine broke after 6 months, but customer service was great.",
        date: "2025-07-08",
        likes: 2,
        dislikes: 3,
        replies: [
          {
            author: "Dave",
            profileImage: "https://i.pravatar.cc/150?img=4",
            question: "What was the issue exactly?",
            date: "2025-07-09",
            likes: 1,
            dislikes: 0,
          },
          {
            author: "Ellen",
            profileImage: "https://i.pravatar.cc/150?img=10",
            question: "Did they replace it for free?",
            date: "2025-07-10",
            likes: 3,
            dislikes: 0,
          },
        ],
      },
    ],
  },
  {
    author: "Eve",
    profileImage: "https://i.pravatar.cc/150?img=5",
    question: "How long does the battery last on a full charge?",
    date: "2025-07-04",
    likes: 9,
    dislikes: 0,
    replies: [
      {
        author: "Frank",
        profileImage: "https://i.pravatar.cc/150?img=6",
        question: "Around 10 hours with moderate use.",
        date: "2025-07-05",
        likes: 4,
        dislikes: 1,
      },
      {
        author: "Admin Tech",
        profileImage: "https://i.pravatar.cc/150?img=51",
        question: "Officially rated for up to 12 hours, depending on usage.",
        date: "2025-07-06",
        isAdmin: true,
        likes: 8,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Grace",
    profileImage: "https://i.pravatar.cc/150?img=7",
    question: "Can this be used outdoors in the rain?",
    date: "2025-07-01",
    likes: 7,
    dislikes: 2,
    replies: [
      {
        author: "Heidi",
        profileImage: "https://i.pravatar.cc/150?img=8",
        question: "Yes, it’s water resistant but avoid heavy downpours.",
        date: "2025-07-02",
        likes: 5,
        dislikes: 0,
      },
      {
        author: "Ivan",
        profileImage: "https://i.pravatar.cc/150?img=9",
        question: "I used it in the rain for a week, and it worked fine.",
        date: "2025-07-03",
        likes: 3,
        dislikes: 0,
      },
      {
        author: "Admin Care",
        profileImage: "https://i.pravatar.cc/150?img=52",
        question: "Please note: while water-resistant, it’s not waterproof.",
        date: "2025-07-04",
        isAdmin: true,
        likes: 6,
        dislikes: 1,
      },
    ],
  },
  {
    author: "Karen",
    profileImage: "https://i.pravatar.cc/150?img=13",
    question: "Does it support Bluetooth 5.0?",
    date: "2025-06-28",
    likes: 10,
    dislikes: 1,
    replies: [
      {
        author: "Leo",
        profileImage: "https://i.pravatar.cc/150?img=14",
        question: "Yes, I paired it with my phone without issues.",
        date: "2025-06-29",
        likes: 2,
        dislikes: 0,
      },
      {
        author: "Mona",
        profileImage: "https://i.pravatar.cc/150?img=15",
        question: "It also supports Bluetooth LE for low power usage.",
        date: "2025-06-30",
        likes: 3,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Nina",
    profileImage: "https://i.pravatar.cc/150?img=16",
    question: "Is the software regularly updated?",
    date: "2025-06-25",
    likes: 11,
    dislikes: 0,
    replies: [
      {
        author: "Oscar",
        profileImage: "https://i.pravatar.cc/150?img=17",
        question: "Yes, got a firmware update last month.",
        date: "2025-06-26",
        likes: 5,
        dislikes: 0,
      },
      {
        author: "Patty",
        profileImage: "https://i.pravatar.cc/150?img=18",
        question: "The app sends notifications when updates are available.",
        date: "2025-06-27",
        likes: 2,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Tom",
    profileImage: "https://i.pravatar.cc/150?img=19",
    question: "What colors are available?",
    date: "2025-06-23",
    likes: 8,
    dislikes: 0,
    replies: [
      {
        author: "Admin Sales",
        profileImage: "https://i.pravatar.cc/150?img=53",
        question: "We offer black, white, and blue currently.",
        date: "2025-06-24",
        isAdmin: true,
        likes: 6,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Lily",
    profileImage: "https://i.pravatar.cc/150?img=20",
    question: "Does it come with a warranty?",
    date: "2025-06-22",
    likes: 7,
    dislikes: 1,
    replies: [
      {
        author: "Admin Support",
        profileImage: "https://i.pravatar.cc/150?img=50",
        question: "Yes, a 1-year manufacturer warranty is included.",
        date: "2025-06-23",
        isAdmin: true,
        likes: 9,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Mark",
    profileImage: "https://i.pravatar.cc/150?img=21",
    question: "How loud is the device during operation?",
    date: "2025-06-20",
    likes: 5,
    dislikes: 2,
    replies: [
      {
        author: "Admin Tech",
        profileImage: "https://i.pravatar.cc/150?img=51",
        question: "It's very quiet, below 30 dB.",
        date: "2025-06-21",
        isAdmin: true,
        likes: 7,
        dislikes: 0,
      },
      {
        author: "Rachel",
        profileImage: "https://i.pravatar.cc/150?img=22",
        question: "I can barely hear it in my office.",
        date: "2025-06-21",
        likes: 3,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Sophia",
    profileImage: "https://i.pravatar.cc/150?img=23",
    question: "Is it easy to clean?",
    date: "2025-06-19",
    likes: 6,
    dislikes: 0,
    replies: [
      {
        author: "Admin Care",
        profileImage: "https://i.pravatar.cc/150?img=52",
        question: "Yes, it has removable parts that are dishwasher safe.",
        date: "2025-06-20",
        isAdmin: true,
        likes: 8,
        dislikes: 0,
      },
    ],
  },
  {
    author: "James",
    profileImage: "https://i.pravatar.cc/150?img=24",
    question: "Can I use it with other devices via USB?",
    date: "2025-06-18",
    likes: 4,
    dislikes: 1,
    replies: [
      {
        author: "Admin Tech",
        profileImage: "https://i.pravatar.cc/150?img=51",
        question: "Yes, it supports USB-C connections with most devices.",
        date: "2025-06-19",
        isAdmin: true,
        likes: 7,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Olivia",
    profileImage: "https://i.pravatar.cc/150?img=25",
    question: "Does it have a companion app?",
    date: "2025-06-17",
    likes: 8,
    dislikes: 0,
    replies: [
      {
        author: "Admin Tech",
        profileImage: "https://i.pravatar.cc/150?img=51",
        question: "Yes, available on iOS and Android with Bluetooth control.",
        date: "2025-06-18",
        isAdmin: true,
        likes: 9,
        dislikes: 0,
      },
      {
        author: "Paul",
        profileImage: "https://i.pravatar.cc/150?img=26",
        question: "The app is intuitive and frequently updated.",
        date: "2025-06-18",
        likes: 5,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Megan",
    profileImage: "https://i.pravatar.cc/150?img=27",
    question: "Can I use it internationally with different voltages?",
    date: "2025-06-15",
    likes: 6,
    dislikes: 0,
    replies: [
      {
        author: "Admin Support",
        profileImage: "https://i.pravatar.cc/150?img=50",
        question: "Yes, it supports 100-240V input worldwide.",
        date: "2025-06-16",
        isAdmin: true,
        likes: 8,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Chris",
    profileImage: "https://i.pravatar.cc/150?img=28",
    question: "Is the screen glare-resistant?",
    date: "2025-06-14",
    likes: 7,
    dislikes: 1,
    replies: [
      {
        author: "Admin Care",
        profileImage: "https://i.pravatar.cc/150?img=52",
        question: "Yes, it has an anti-glare coating for outdoor use.",
        date: "2025-06-15",
        isAdmin: true,
        likes: 6,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Jessica",
    profileImage: "https://i.pravatar.cc/150?img=29",
    question: "How fast is the charging time?",
    date: "2025-06-12",
    likes: 9,
    dislikes: 0,
    replies: [
      {
        author: "Admin Tech",
        profileImage: "https://i.pravatar.cc/150?img=51",
        question: "About 2 hours with the included fast charger.",
        date: "2025-06-13",
        isAdmin: true,
        likes: 7,
        dislikes: 0,
      },
    ],
  },
];

export default exampleQuestions;
