    // countries.ts

    export interface Country {
    code: string;
    label: string;
    dialCode: string;
    flag: string;
    }

    const countries: Country[] = [
    { code: 'AF', label: 'Afghanistan', dialCode: '+93', flag: '🇦🇫' },
    { code: 'AL', label: 'Albania', dialCode: '+355', flag: '🇦🇱' },
    { code: 'DZ', label: 'Algeria', dialCode: '+213', flag: '🇩🇿' },
    { code: 'AS', label: 'American Samoa', dialCode: '+1 684', flag: '🇦🇸' },
    { code: 'AD', label: 'Andorra', dialCode: '+376', flag: '🇦🇩' },
    { code: 'AO', label: 'Angola', dialCode: '+244', flag: '🇦🇴' },
    { code: 'AI', label: 'Anguilla', dialCode: '+1 264', flag: '🇦🇮' },
    { code: 'AQ', label: 'Antarctica', dialCode: '+672', flag: '🇦🇶' },
    { code: 'AG', label: 'Antigua and Barbuda', dialCode: '+1 268', flag: '🇦🇬' },
    { code: 'AR', label: 'Argentina', dialCode: '+54', flag: '🇦🇷' },
    { code: 'AM', label: 'Armenia', dialCode: '+374', flag: '🇦🇲' },
    { code: 'AW', label: 'Aruba', dialCode: '+297', flag: '🇦🇼' },
    { code: 'AU', label: 'Australia', dialCode: '+61', flag: '🇦🇺' },
    { code: 'AT', label: 'Austria', dialCode: '+43', flag: '🇦🇹' },
    { code: 'AZ', label: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿' },
    { code: 'BS', label: 'Bahamas', dialCode: '+1 242', flag: '🇧🇸' },
    { code: 'BH', label: 'Bahrain', dialCode: '+973', flag: '🇧🇭' },
    { code: 'BD', label: 'Bangladesh', dialCode: '+880', flag: '🇧🇩' },
    { code: 'BB', label: 'Barbados', dialCode: '+1 246', flag: '🇧🇧' },
    { code: 'BY', label: 'Belarus', dialCode: '+375', flag: '🇧🇾' },
    { code: 'BE', label: 'Belgium', dialCode: '+32', flag: '🇧🇪' },
    { code: 'BZ', label: 'Belize', dialCode: '+501', flag: '🇧🇿' },
    { code: 'BJ', label: 'Benin', dialCode: '+229', flag: '🇧🇯' },
    { code: 'BM', label: 'Bermuda', dialCode: '+1 441', flag: '🇧🇲' },
    { code: 'BT', label: 'Bhutan', dialCode: '+975', flag: '🇧🇹' },
    { code: 'BO', label: 'Bolivia', dialCode: '+591', flag: '🇧🇴' },
    { code: 'BA', label: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦' },
    { code: 'BW', label: 'Botswana', dialCode: '+267', flag: '🇧🇼' },
    { code: 'BV', label: 'Bouvet Island', dialCode: '+47', flag: '🇧🇻' },
    { code: 'BR', label: 'Brazil', dialCode: '+55', flag: '🇧🇷' },
    { code: 'IO', label: 'British Indian Ocean Territory', dialCode: '+246', flag: '🇮🇴' },
    { code: 'BN', label: 'Brunei Darussalam', dialCode: '+673', flag: '🇧🇳' },
    { code: 'BG', label: 'Bulgaria', dialCode: '+359', flag: '🇧🇬' },
    { code: 'BF', label: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫' },
    { code: 'BI', label: 'Burundi', dialCode: '+257', flag: '🇧🇮' },
    { code: 'KH', label: 'Cambodia', dialCode: '+855', flag: '🇰🇭' },
    { code: 'CM', label: 'Cameroon', dialCode: '+237', flag: '🇨🇲' },
    { code: 'CA', label: 'Canada', dialCode: '+1', flag: '🇨🇦' },
    { code: 'CV', label: 'Cape Verde', dialCode: '+238', flag: '🇨🇻' },
    { code: 'KY', label: 'Cayman Islands', dialCode: '+1 345', flag: '🇰🇾' },
    { code: 'CF', label: 'Central African Republic', dialCode: '+236', flag: '🇨🇫' },
    { code: 'TD', label: 'Chad', dialCode: '+235', flag: '🇹🇩' },
    { code: 'CL', label: 'Chile', dialCode: '+56', flag: '🇨🇱' },
    { code: 'CN', label: 'China', dialCode: '+86', flag: '🇨🇳' },
    { code: 'CX', label: 'Christmas Island', dialCode: '+61', flag: '🇨🇽' },
    { code: 'CC', label: 'Cocos (Keeling) Islands', dialCode: '+61', flag: '🇨🇨' },
    { code: 'CO', label: 'Colombia', dialCode: '+57', flag: '🇨🇴' },
    { code: 'KM', label: 'Comoros', dialCode: '+269', flag: '🇰🇲' },
    { code: 'CG', label: 'Congo', dialCode: '+242', flag: '🇨🇬' },
    { code: 'CD', label: 'Congo (Democratic Republic)', dialCode: '+243', flag: '🇨🇩' },
    { code: 'CK', label: 'Cook Islands', dialCode: '+682', flag: '🇨🇰' },
    { code: 'CR', label: 'Costa Rica', dialCode: '+506', flag: '🇨🇷' },
    { code: 'HR', label: 'Croatia', dialCode: '+385', flag: '🇭🇷' },
    { code: 'CU', label: 'Cuba', dialCode: '+53', flag: '🇨🇺' },
    { code: 'CW', label: 'Curaçao', dialCode: '+599', flag: '🇨🇼' },
    { code: 'CY', label: 'Cyprus', dialCode: '+357', flag: '🇨🇾' },
    { code: 'CZ', label: 'Czech Republic', dialCode: '+420', flag: '🇨🇿' },
    { code: 'CI', label: 'Côte d\'Ivoire', dialCode: '+225', flag: '🇨🇮' },
    { code: 'DK', label: 'Denmark', dialCode: '+45', flag: '🇩🇰' },
    { code: 'DJ', label: 'Djibouti', dialCode: '+253', flag: '🇩🇯' },
    { code: 'DM', label: 'Dominica', dialCode: '+1 767', flag: '🇩🇲' },
    { code: 'DO', label: 'Dominican Republic', dialCode: '+1 809', flag: '🇩🇴' },
    { code: 'EC', label: 'Ecuador', dialCode: '+593', flag: '🇪🇨' },
    { code: 'EG', label: 'Egypt', dialCode: '+20', flag: '🇪🇬' },
    { code: 'SV', label: 'El Salvador', dialCode: '+503', flag: '🇸🇻' },
    { code: 'GQ', label: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶' },
    { code: 'ER', label: 'Eritrea', dialCode: '+291', flag: '🇪🇷' },
    { code: 'EE', label: 'Estonia', dialCode: '+372', flag: '🇪🇪' },
    { code: 'SZ', label: 'Eswatini', dialCode: '+268', flag: '🇸🇿' },
    { code: 'ET', label: 'Ethiopia', dialCode: '+251', flag: '🇪🇹' },
    { code: 'FK', label: 'Falkland Islands', dialCode: '+500', flag: '🇫🇰' },
    { code: 'FO', label: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴' },
    { code: 'FJ', label: 'Fiji', dialCode: '+679', flag: '🇫🇯' },
    { code: 'FI', label: 'Finland', dialCode: '+358', flag: '🇫🇮' },
    { code: 'FR', label: 'France', dialCode: '+33', flag: '🇫🇷'},
        { code: 'GF', label: 'French Guiana', dialCode: '+594', flag: '🇬🇫' },
        { code: 'PF', label: 'French Polynesia', dialCode: '+689', flag: '🇵🇫' },
        { code: 'TF', label: 'French Southern Territories', dialCode: '+262', flag: '🇹🇫' },
        { code: 'GA', label: 'Gabon', dialCode: '+241', flag: '🇬🇦' },
        { code: 'GM', label: 'Gambia', dialCode: '+220', flag: '🇬🇲' },
        { code: 'GE', label: 'Georgia', dialCode: '+995', flag: '🇬🇪' },
        { code: 'DE', label: 'Germany', dialCode: '+49', flag: '🇩🇪' },
        { code: 'GH', label: 'Ghana', dialCode: '+233', flag: '🇬🇭' },
        { code: 'GI', label: 'Gibraltar', dialCode: '+350', flag: '🇬🇮' },
        { code: 'GR', label: 'Greece', dialCode: '+30', flag: '🇬🇷' },
        { code: 'GL', label: 'Greenland', dialCode: '+299', flag: '🇬🇱' },
        { code: 'GD', label: 'Grenada', dialCode: '+1 473', flag: '🇬🇩' },
        { code: 'GP', label: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵' },
        { code: 'GU', label: 'Guam', dialCode: '+1 671', flag: '🇬🇺' },
        { code: 'GT', label: 'Guatemala', dialCode: '+502', flag: '🇬🇹' },
        { code: 'GG', label: 'Guernsey', dialCode: '+44', flag: '🇬🇬' },
        { code: 'GN', label: 'Guinea', dialCode: '+224', flag: '🇬🇳' },
        { code: 'GW', label: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼' },
        { code: 'GY', label: 'Guyana', dialCode: '+592', flag: '🇬🇾' },
        { code: 'HT', label: 'Haiti', dialCode: '+509', flag: '🇭🇹' },
        { code: 'HM', label: 'Heard Island and McDonald Islands', dialCode: '+672', flag: '🇭🇲' },
        { code: 'VA', label: 'Holy See', dialCode: '+379', flag: '🇻🇦' },
        { code: 'HN', label: 'Honduras', dialCode: '+504', flag: '🇭🇳' },
        { code: 'HK', label: 'Hong Kong', dialCode: '+852', flag: '🇭🇰' },
        { code: 'HU', label: 'Hungary', dialCode: '+36', flag: '🇭🇺' },
        { code: 'IS', label: 'Iceland', dialCode: '+354', flag: '🇮🇸' },
        { code: 'IN', label: 'India', dialCode: '+91', flag: '🇮🇳' },
        { code: 'ID', label: 'Indonesia', dialCode: '+62', flag: '🇮🇩' },
        { code: 'IR', label: 'Iran', dialCode: '+98', flag: '🇮🇷' },
        { code: 'IQ', label: 'Iraq', dialCode: '+964', flag: '🇮🇶' },
        { code: 'IE', label: 'Ireland', dialCode: '+353', flag: '🇮🇪' },
        { code: 'IM', label: 'Isle of Man', dialCode: '+44', flag: '🇮🇲' },
        { code: 'IL', label: 'Israel', dialCode: '+972', flag: '🇮🇱' },
        { code: 'IT', label: 'Italy', dialCode: '+39', flag: '🇮🇹' },
        { code: 'JM', label: 'Jamaica', dialCode: '+1 876', flag: '🇯🇲' },
        { code: 'JP', label: 'Japan', dialCode: '+81', flag: '🇯🇵' },
        { code: 'JE', label: 'Jersey', dialCode: '+44', flag: '🇯🇪' },
        { code: 'JO', label: 'Jordan', dialCode: '+962', flag: '🇯🇴' },
        { code: 'KZ', label: 'Kazakhstan', dialCode: '+7', flag: '🇰🇿' },
        { code: 'KE', label: 'Kenya', dialCode: '+254', flag: '🇰🇪' },
        { code: 'KI', label: 'Kiribati', dialCode: '+686', flag: '🇰🇮' },
        { code: 'KP', label: 'North Korea', dialCode: '+850', flag: '🇰🇵' },
        { code: 'KR', label: 'South Korea', dialCode: '+82', flag: '🇰🇷' },
        { code: 'KW', label: 'Kuwait', dialCode: '+965', flag: '🇰🇼' },
        { code: 'KG', label: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬' },
        { code: 'LA', label: 'Laos', dialCode: '+856', flag: '🇱🇦' },
        { code: 'LV', label: 'Latvia', dialCode: '+371', flag: '🇱🇻' },
        { code: 'LB', label: 'Lebanon', dialCode: '+961', flag: '🇱🇧' },
        { code: 'LS', label: 'Lesotho', dialCode: '+266', flag: '🇱🇸' },
        { code: 'LR', label: 'Liberia', dialCode: '+231', flag: '🇱🇷' },
        { code: 'LY', label: 'Libya', dialCode: '+218', flag: '🇱🇾' },
        { code: 'LI', label: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮' },
        { code: 'LT', label: 'Lithuania', dialCode: '+370', flag: '🇱🇹' },
        { code: 'LU', label: 'Luxembourg', dialCode: '+352', flag: '🇱🇺' },
        { code: 'MO', label: 'Macau', dialCode: '+853', flag: '🇲🇴' },
        { code: 'MG', label: 'Madagascar', dialCode: '+261', flag: '🇲🇬' },
        { code: 'MW', label: 'Malawi', dialCode: '+265', flag: '🇲🇼' },
        { code: 'MY', label: 'Malaysia', dialCode: '+60', flag: '🇲🇾' },
        { code: 'MV', label: 'Maldives', dialCode: '+960', flag: '🇲🇻' },
        { code: 'ML', label: 'Mali', dialCode: '+223', flag: '🇲🇱' },
        { code: 'MT', label: 'Malta', dialCode: '+356', flag: '🇲🇹' },
        { code: 'MH', label: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭' },
        { code: 'MQ', label: 'Martinique', dialCode: '+596', flag: '🇲🇶' },
        { code: 'MR', label: 'Mauritania', dialCode: '+222', flag: '🇲🇷' },
        { code: 'MU', label: 'Mauritius', dialCode: '+230', flag: '🇲🇺' },
        { code: 'YT', label: 'Mayotte', dialCode: '+262', flag: '🇾🇹' },
        { code: 'MX', label: 'Mexico', dialCode: '+52', flag: '🇲🇽' },
        { code: 'FM', label: 'Micronesia', dialCode: '+691', flag: '🇫🇲' },
        { code: 'MD', label: 'Moldova', dialCode: '+373', flag: '🇲🇩' },
        { code: 'MC', label: 'Monaco', dialCode: '+377', flag: '🇲🇨' },
        { code: 'MN', label: 'Mongolia', dialCode: '+976', flag: '🇲🇳' },
        { code: 'ME', label: 'Montenegro', dialCode: '+382', flag: '🇲🇪' },
        { code: 'MS', label: 'Montserrat', dialCode: '+1 664', flag: '🇲🇸' },
        { code: 'MA', label: 'Morocco', dialCode: '+212', flag: '🇲🇦' },
        { code: 'MZ', label: 'Mozambique', dialCode: '+258', flag: '🇲🇿' },
        { code: 'MM', label: 'Myanmar', dialCode: '+95', flag: '🇲🇲' },
        { code: 'NA', label: 'Namibia', dialCode: '+264', flag: '🇳🇦' },
        { code: 'NR', label: 'Nauru', dialCode: '+674', flag: '🇳🇷' },
        { code: 'NP', label: 'Nepal', dialCode: '+977', flag: '🇳🇵' },
        { code: 'NL', label: 'Netherlands', dialCode: '+31', flag: '🇳🇱' },
        { code: 'NC', label: 'New Caledonia', dialCode: '+687', flag: '🇳🇨' },
        { code: 'NZ', label: 'New Zealand', dialCode: '+64', flag: '🇳🇿' },
        { code: 'NI', label: 'Nicaragua', dialCode: '+505', flag: '🇳🇮' },
        { code: 'NE', label: 'Niger', dialCode: '+227', flag: '🇳🇪' },
        { code: 'NG', label: 'Nigeria', dialCode: '+234', flag: '🇳🇬' },
        { code: 'NU', label: 'Niue', dialCode: '+683', flag: '🇳🇺' },
        { code: 'NF', label: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫' },
        { code: 'MP', label: 'Northern Mariana Islands', dialCode: '+1 670', flag: '🇲🇵' },
        { code: 'NO', label: 'Norway', dialCode: '+47', flag: '🇳🇴' },
        { code: 'OM', label: 'Oman', dialCode: '+968', flag: '🇴🇲' },
        { code: 'PK', label: 'Pakistan', dialCode: '+92', flag: '🇵🇰' },
        { code: 'PW', label: 'Palau', dialCode: '+680', flag: '🇵🇼' },
        { code: 'PS', label: 'Palestine', dialCode: '+970', flag: '🇵🇸' },
        { code: 'PA', label: 'Panama', dialCode: '+507', flag: '🇵🇦' },
        { code: 'PG', label: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬' },
        { code: 'PY', label: 'Paraguay', dialCode: '+595', flag: '🇵🇾' },
        { code: 'PE', label: 'Peru', dialCode: '+51', flag: '🇵🇪' },
        { code: 'PH', label: 'Philippines', dialCode: '+63', flag: '🇵🇭' },
        { code: 'PN', label: 'Pitcairn', dialCode: '+64', flag: '🇵🇳' },
        { code: 'PL', label: 'Poland', dialCode: '+48', flag: '🇵🇱' },
        { code: 'PT', label: 'Portugal', dialCode: '+351', flag: '🇵🇹' },
        { code: 'PR', label: 'Puerto Rico', dialCode: '+1 787', flag: '🇵🇷' },
        { code: 'QA', label: 'Qatar', dialCode: '+974', flag: '🇶🇦' },
        { code: 'RE', label: 'Réunion', dialCode: '+262', flag: '🇷🇪' },
        { code: 'RO', label: 'Romania', dialCode: '+40', flag: '🇷🇴' },
        { code: 'RU', label: 'Russia', dialCode: '+7', flag: '🇷🇺' },
        { code: 'RW', label: 'Rwanda', dialCode: '+250', flag: '🇷🇼' },
        { code: 'BL', label: 'Saint Barthélemy', dialCode: '+590', flag: '🇧🇱' },
        { code: 'SH', label: 'Saint Helena', dialCode: '+290', flag: '🇸🇭' },
        { code: 'KN', label: 'Saint Kitts and Nevis', dialCode: '+1 869', flag: '🇰🇳' },
        { code: 'LC', label: 'Saint Lucia', dialCode: '+1 758', flag: '🇱🇨' },
        { code: 'MF', label: 'Saint Martin', dialCode: '+590', flag: '🇲🇫' },
        { code: 'PM', label: 'Saint Pierre and Miquelon', dialCode: '+508', flag: '🇵🇲' },
        { code: 'VC', label: 'Saint Vincent and the Grenadines', dialCode: '+1 784', flag: '🇻🇨' },
        { code: 'WS', label: 'Samoa', dialCode: '+685', flag: '🇼🇸' },
        { code: 'SM', label: 'San Marino', dialCode: '+378', flag: '🇸🇲' },
        { code: 'ST', label: 'Sao Tome and Principe', dialCode: '+239', flag: '🇸🇹' },
        { code: 'SA', label: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦' },
        { code: 'SN', label: 'Senegal', dialCode: '+221', flag: '🇸🇳' },
        { code: 'RS', label: 'Serbia', dialCode: '+381', flag: '🇷🇸' },
        { code: 'SC', label: 'Seychelles', dialCode: '+248', flag: '🇸🇨' },
        { code: 'SL', label: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱' },
        { code: 'SG', label: 'Singapore', dialCode: '+65', flag: '🇸🇬' },
        { code: 'SX', label: 'Sint Maarten', dialCode: '+1 721', flag: '🇸🇽' },
        { code: 'SK', label: 'Slovakia', dialCode: '+421', flag: '🇸🇰' },
        { code: 'SI', label: 'Slovenia', dialCode: '+386', flag: '🇸🇮' },
        { code: 'SB', label: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧' },
        { code: 'SO', label: 'Somalia', dialCode: '+252', flag: '🇸🇴' },
        { code: 'ZA', label: 'South Africa', dialCode: '+27', flag: '🇿🇦' },
        { code: 'GS', label: 'South Georgia and the South Sandwich Islands', dialCode: '+500', flag: '🇬🇸' },
        { code: 'SS', label: 'South Sudan', dialCode: '+211', flag: '🇸🇸' },
        { code: 'ES', label: 'Spain', dialCode: '+34', flag: '🇪🇸' },
        { code: 'LK', label: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰' },
        { code: 'SD', label: 'Sudan', dialCode: '+249', flag: '🇸🇩' },
        { code: 'SR', label: 'Suriname', dialCode: '+597', flag: '🇸🇷' },
        { code: 'SJ', label: 'Svalbard and Jan Mayen', dialCode: '+47', flag: '🇸🇯' },
        { code: 'SE', label: 'Sweden', dialCode: '+46', flag: '🇸🇪' },
        { code: 'CH', label: 'Switzerland', dialCode: '+41', flag: '🇨🇭' },
        { code: 'SY', label: 'Syria', dialCode: '+963', flag: '🇸🇾' },
        { code: 'TW', label: 'Taiwan', dialCode: '+886', flag: '🇹🇼' },
        { code: 'TJ', label: 'Tajikistan', dialCode: '+992', flag: '🇹🇯' },
        { code: 'TZ', label: 'Tanzania', dialCode: '+255', flag: '🇹🇿' },
        { code: 'TH', label: 'Thailand', dialCode: '+66', flag: '🇹🇭' },
        { code: 'TL', label: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱' },
        { code: 'TG', label: 'Togo', dialCode: '+228', flag: '🇹🇬' },
        { code: 'TK', label: 'Tokelau', dialCode: '+690', flag: '🇹🇰' },
        { code: 'TO', label: 'Tonga', dialCode: '+676', flag: '🇹🇴' },
        { code: 'TT', label: 'Trinidad and Tobago', dialCode: '+1 868', flag: '🇹🇹' },
        { code: 'TN', label: 'Tunisia', dialCode: '+216', flag: '🇹🇳' },
        { code: 'TR', label: 'Turkey', dialCode: '+90', flag: '🇹🇷' },
        { code: 'TM', label: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲' },
        { code: 'TC', label: 'Turks and Caicos Islands', dialCode: '+1 649', flag: '🇹🇨' },
        { code: 'TV', label: 'Tuvalu', dialCode: '+688', flag: '🇹🇻' },
        { code: 'UG', label: 'Uganda', dialCode: '+256', flag: '🇺🇬' },
        { code: 'UA', label: 'Ukraine', dialCode: '+380', flag: '🇺🇦' },
        { code: 'AE', label: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪' },
        { code: 'GB', label: 'United Kingdom', dialCode: '+44', flag: '🇬🇧' },
        { code: 'US', label: 'United States', dialCode: '+1', flag: '🇺🇸' },
        { code: 'UY', label: 'Uruguay', dialCode: '+598', flag: '🇺🇾' },
        { code: 'UZ', label: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿' },
        { code: 'VU', label: 'Vanuatu', dialCode: '+678', flag: '🇻🇺' },
        { code: 'VE', label: 'Venezuela', dialCode: '+58', flag: '🇻🇪' },
        { code: 'VN', label: 'Vietnam', dialCode: '+84', flag: '🇻🇳' },
        { code: 'VG', label: 'British Virgin Islands', dialCode: '+1 284', flag: '🇻🇬' },
        { code: 'VI', label: 'U.S. Virgin Islands', dialCode: '+1 340', flag: '🇻🇮' },
        { code: 'WF', label: 'Wallis and Futuna', dialCode: '+681', flag: '🇼🇫' },
        { code: 'EH', label: 'Western Sahara', dialCode: '+212', flag: '🇪🇭' },
        { code: 'YE', label: 'Yemen', dialCode: '+967', flag: '🇾🇪' },
        { code: 'ZM', label: 'Zambia', dialCode: '+260', flag: '🇿🇲' },
        { code: 'ZW', label: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼' },
    ];

    export default countries;
