export const placeholderReviews: Review[] = [
  {
    author: "Emily Carter",
    profileImage: "https://i.pravatar.cc/150?img=44",
    rating: 5,
    comment:
      "Absolutely love this product! It arrived quickly and works perfectly. I’ve recommended it to all my friends and family.",
    date: "2022-06-21T19:00:00",
    verified: true,
    likes: 112,
    dislikes: 4,
    replies: [
      {
        author: "Admin Jane",
        profileImage: "https://i.pravatar.cc/150?img=10",
        rating: 0,
        comment:
          "Thank you so much for your wonderful feedback, Emily! We’re thrilled to hear you're enjoying it.",
        date: "2022-06-22T10:30:00",
        isAdmin: true,
        likes: 18,
        dislikes: 0,
        replies: [
          {
            author: "Emily Carter",
            profileImage: "https://i.pravatar.cc/150?img=44",
            rating: 0,
            comment:
              "You're welcome! Keep up the great service. I'll definitely order again soon.",
            date: "2022-06-22T12:00:00",
            verified: true,
            likes: 9,
            dislikes: 1,
          },
        ],
      },
      {
        author: "Tom Hanks",
        profileImage: "https://i.pravatar.cc/150?img=15",
        rating: 0,
        comment: "I agree with Emily, excellent product and fast shipping!",
        date: "2022-06-23T14:15:00",
        verified: true,
        likes: 42,
        dislikes: 2,
      },
    ],
  },
  {
    author: "Jake Nguyen",
    profileImage: "https://i.pravatar.cc/150?img=32",
    rating: 4,
    comment:
      "Really good quality. Lost one star because the packaging was a bit damaged on arrival, but the product inside was fine.",
    date: "2021-06-10T08:20:00",
    verified: true,
    likes: 67,
    dislikes: 18,
    replies: [
      {
        author: "Admin Kate",
        profileImage: "https://i.pravatar.cc/150?img=12",
        rating: 0,
        comment:
          "Thanks for the honest review, Jake. We apologize for the packaging issue and will work on improving it.",
        date: "2021-06-11T09:00:00",
        isAdmin: true,
        likes: 14,
        dislikes: 0,
        replies: [
          {
            author: "Jake Nguyen",
            profileImage: "https://i.pravatar.cc/150?img=32",
            rating: 0,
            comment:
              "Appreciate the response! Hope future shipments are better.",
            date: "2021-06-11T11:30:00",
            verified: true,
            likes: 5,
            dislikes: 0,
          },
        ],
      },
    ],
  },
  {
    author: "Sophie Lee",
    profileImage: "https://i.pravatar.cc/150?img=51",
    rating: 5,
    comment:
      "Exceeded my expectations in every way! The build quality is solid and the customer support was very responsive.",
    date: "2025-07-01T20:45:00",
    verified: true,
    likes: 203,
    dislikes: 7,
    replies: [
      {
        author: "Admin Leo",
        profileImage: "https://i.pravatar.cc/150?img=13",
        rating: 0,
        comment:
          "Thanks Sophie! We’re glad to hear you had a great experience. Let us know if you need anything else.",
        date: "2025-07-02T09:00:00",
        isAdmin: true,
        likes: 25,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Mark Thompson",
    profileImage: "https://i.pravatar.cc/150?img=5",
    rating: 3,
    comment:
      "Product is decent but shipping was delayed by a week. Support was helpful but could be faster.",
    date: "2023-06-15T13:30:00",
    verified: true,
    likes: 28,
    dislikes: 33,
    replies: [
      {
        author: "Admin Lisa",
        profileImage: "https://i.pravatar.cc/150?img=9",
        rating: 0,
        comment:
          "Sorry for the delay, Mark. We’re working with our shipping partners to speed things up.",
        date: "2023-06-16T08:00:00",
        isAdmin: true,
        likes: 10,
        dislikes: 2,
        replies: [
          {
            author: "Mark Thompson",
            profileImage: "https://i.pravatar.cc/150?img=5",
            rating: 0,
            comment:
              "Thanks for the update. I hope things improve soon.",
            date: "2023-06-16T12:30:00",
            verified: true,
            likes: 4,
            dislikes: 0,
          },
        ],
      },
    ],
  },
  {
    author: "New User",
    profileImage: "https://i.pravatar.cc/150?img=7",
    rating: 5,
    comment: "Just bought this and love it already! Highly recommend!",
    date: "2024-07-05T19:30:00",
    verified: true,
    likes: 39,
    dislikes: 3,
  },
  {
    author: "Anna Wilson",
    profileImage: "https://i.pravatar.cc/150?img=22",
    rating: 4,
    comment:
      "Good product, works well but a bit pricey. I hope prices go down in future.",
    date: "2023-11-11T16:00:00",
    verified: true,
    likes: 51,
    dislikes: 4,
  },
  {
    author: "George Martin",
    profileImage: "https://i.pravatar.cc/150?img=28",
    rating: 2,
    comment:
      "Did not meet my expectations. The product stopped working after 2 months. Customer service was helpful but couldn't resolve it fully.",
    date: "2022-09-20T12:10:00",
    verified: true,
    likes: 15,
    dislikes: 20,
    replies: [
      {
        author: "Admin Sam",
        profileImage: "https://i.pravatar.cc/150?img=11",
        rating: 0,
        comment:
          "Sorry to hear that, George. Please contact us again for a possible replacement.",
        date: "2022-09-21T09:15:00",
        isAdmin: true,
        likes: 7,
        dislikes: 1,
        replies: [
          {
            author: "George Martin",
            profileImage: "https://i.pravatar.cc/150?img=28",
            rating: 0,
            comment: "Thanks for the follow-up, I’m trying that now.",
            date: "2022-09-22T10:00:00",
            verified: true,
            likes: 2,
            dislikes: 0,
          },
        ],
      },
    ],
  },
  {
    author: "Lisa Simpson",
    profileImage: "https://i.pravatar.cc/150?img=35",
    rating: 5,
    comment: "Perfect! Exactly what I needed, will order again.",
    date: "2025-01-25T09:30:00",
    verified: true,
    likes: 88,
    dislikes: 2,
  },
  {
    author: "Michael Brown",
    profileImage: "https://i.pravatar.cc/150?img=40",
    rating: 3,
    comment: "Average quality, might consider alternatives next time.",
    date: "2024-03-10T11:45:00",
    verified: true,
    likes: 21,
    dislikes: 10,
  },
  {
    author: "Jessica Taylor",
    profileImage: "https://i.pravatar.cc/150?img=27",
    rating: 4,
    comment: "Good product with minor flaws but generally happy.",
    date: "2023-05-17T14:00:00",
    verified: true,
    likes: 43,
    dislikes: 5,
  },
  {
    author: "David Anderson",
    profileImage: "https://i.pravatar.cc/150?img=12",
    rating: 5,
    comment: "Highly recommend this to everyone! Great quality and service.",
    date: "2025-06-12T18:20:00",
    verified: true,
    likes: 150,
    dislikes: 2,
    replies: [
      {
        author: "Admin Rachel",
        profileImage: "https://i.pravatar.cc/150?img=16",
        rating: 0,
        comment:
          "Thank you for the great recommendation, David! We’re glad you’re happy with our service.",
        date: "2025-06-13T09:00:00",
        isAdmin: true,
        likes: 25,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Rachel Green",
    profileImage: "https://i.pravatar.cc/150?img=18",
    rating: 1,
    comment: "Very disappointed with the purchase. Not as described.",
    date: "2021-12-05T10:00:00",
    verified: true,
    likes: 7,
    dislikes: 40,
    replies: [
      {
        author: "Admin Kate",
        profileImage: "https://i.pravatar.cc/150?img=12",
        rating: 0,
        comment:
          "We’re sorry you had a bad experience. Please reach out so we can make it right.",
        date: "2021-12-06T09:00:00",
        isAdmin: true,
        likes: 12,
        dislikes: 0,
        replies: [
          {
            author: "Rachel Green",
            profileImage: "https://i.pravatar.cc/150?img=18",
            rating: 0,
            comment:
              "Thanks, I contacted support and they resolved the issue quickly.",
            date: "2021-12-07T14:00:00",
            verified: true,
            likes: 5,
            dislikes: 0,
          },
        ],
      },
    ],
  },
  {
    author: "Chris Evans",
    profileImage: "https://i.pravatar.cc/150?img=8",
    rating: 4,
    comment: "Works well, fast shipping, good overall experience.",
    date: "2024-08-22T13:10:00",
    verified: true,
    likes: 60,
    dislikes: 1,
  },
  {
    author: "Samantha Fox",
    profileImage: "https://i.pravatar.cc/150?img=26",
    rating: 3,
    comment: "It's okay, nothing special. You get what you pay for.",
    date: "2023-07-07T17:50:00",
    verified: true,
    likes: 24,
    dislikes: 8,
  },
  {
    author: "Oliver Queen",
    profileImage: "https://i.pravatar.cc/150?img=9",
    rating: 5,
    comment: "Exceeded expectations in every way. Highly recommend.",
    date: "2025-02-28T15:25:00",
    verified: true,
    likes: 132,
    dislikes: 3,
    replies: [
      {
        author: "Admin Oliver",
        profileImage: "https://i.pravatar.cc/150?img=20",
        rating: 0,
        comment:
          "Thanks for your endorsement! We aim to keep exceeding expectations.",
        date: "2025-03-01T08:30:00",
        isAdmin: true,
        likes: 18,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Zara Khan",
    profileImage: "https://i.pravatar.cc/150?img=45",
    rating: 4,
    comment:
      "Very good product, I am mostly satisfied but delivery took longer than expected.",
    date: "2023-03-30T14:00:00",
    verified: true,
    likes: 37,
    dislikes: 4,
    replies: [
      {
        author: "Admin Mike",
        profileImage: "https://i.pravatar.cc/150?img=16",
        rating: 0,
        comment:
          "Thanks for your feedback, Zara. We’re working on improving our shipping times.",
        date: "2023-03-31T09:00:00",
        isAdmin: true,
        likes: 10,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Peter Parker",
    profileImage: "https://i.pravatar.cc/150?img=19",
    rating: 5,
    comment: "Amazing! Exactly what I needed for my collection.",
    date: "2024-12-12T19:40:00",
    verified: true,
    likes: 95,
    dislikes: 1,
  },
  {
    author: "Karen Hill",
    profileImage: "https://i.pravatar.cc/150?img=21",
    rating: 2,
    comment:
      "Not very durable, had to replace after a month. Customer service was decent.",
    date: "2022-08-18T11:20:00",
    verified: true,
    likes: 14,
    dislikes: 29,
    replies: [
      {
        author: "Admin Rachel",
        profileImage: "https://i.pravatar.cc/150?img=16",
        rating: 0,
        comment:
          "Sorry to hear about your experience, Karen. We're here if you want to discuss further.",
        date: "2022-08-19T08:00:00",
        isAdmin: true,
        likes: 5,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Frank Castle",
    profileImage: "https://i.pravatar.cc/150?img=13",
    rating: 5,
    comment:
      "Outstanding product! The attention to detail and quality is unmatched.",
    date: "2025-04-10T13:00:00",
    verified: true,
    likes: 160,
    dislikes: 2,
  },
  {
    author: "Nancy Drew",
    profileImage: "https://i.pravatar.cc/150?img=30",
    rating: 4,
    comment:
      "Works as described. A few minor issues but overall very happy with the purchase.",
    date: "2024-11-05T10:30:00",
    verified: true,
    likes: 49,
    dislikes: 3,
  },
  {
    author: "Bruce Wayne",
    profileImage: "https://i.pravatar.cc/150?img=2",
    rating: 5,
    comment:
      "The product is excellent and the service top-notch. Will buy again.",
    date: "2025-05-20T21:10:00",
    verified: true,
    likes: 175,
    dislikes: 1,
    replies: [
      {
        author: "Admin Bruce",
        profileImage: "https://i.pravatar.cc/150?img=1",
        rating: 0,
        comment:
          "Thank you for your loyalty, Mr. Wayne! We appreciate your continued support.",
        date: "2025-05-21T08:00:00",
        isAdmin: true,
        likes: 20,
        dislikes: 0,
      },
    ],
  },
  {
    author: "Megan Fox",
    profileImage: "https://i.pravatar.cc/150?img=38",
    rating: 3,
    comment:
      "Product is okay but not worth the price. There are cheaper alternatives.",
    date: "2023-09-15T16:25:00",
    verified: true,
    likes: 18,
    dislikes: 14,
  },
  {
    author: "Tony Stark",
    profileImage: "https://i.pravatar.cc/150?img=23",
    rating: 5,
    comment:
      "High quality and stylish design. Exactly what I was looking for.",
    date: "2025-06-01T12:30:00",
    verified: true,
    likes: 155,
    dislikes: 0,
  },
];
